### ISSUE TITLE
Where does the topic iiwa/joint_states publish? In which folder can I find this command?

### ISSUE THREAD

**Issue by mf093087** [epfl-lasa/iiwa_ros#76]
![image](https://user-images.githubusercontent.com/67538561/147565743-e02aab95-54be-477e-bebc-4c62ee1cd8ab.png)
Where does the topic iiwa/joint_states publish? In which folder can I find this command?

**Comment by costashatz** [comment]
Hello,

This is not a specific command. We are using the ros_control interface (see docs [here](http://wiki.ros.org/ros_control)), which is the main framework of ROS for handling controllers. One of the "controllers" (I put it in quotes, because this is not really a controller) is the "joint_state_controller" (see [here](http://wiki.ros.org/joint_state_controller)). This controller creates this topic that has the latest value of the joint states.

In **iiwa_ros** we use this through the configuration files (for an example see [here](https://github.com/epfl-lasa/iiwa_ros/blob/master/iiwa_control/config/iiwa_control.yaml#L3-L5)), and in the ros_control interface in the C++ code (see [here](https://github.com/epfl-lasa/iiwa_ros/blob/master/iiwa_driver/src/iiwa.cpp#L283-L287) for the real robot driver; the simulated ones in Gazebo have this automatically filled by the simulation).

Hope that this is clear, but you really need to give the ROS docs a good and deep look before using iiwa_ros.

Happy New Year!
